### ISSUE TITLE
Contact me doesn't work.  (PHP not supported on github pages)

### ISSUE THREAD

**Issue by waterlgndx** [w3develops/w3develops#88]
The contact me at the bottom of the site doesn't work because GitHub doesn't support php.  I could host this aspect (and any other php features you might need) if you want.  Oh but if I did this I think it'd be a good idea to add a subdomain to w3develops and point it to the external host.

**Comment by waterlgndx** [comment]
There are also pre-existing hosts that let you collect form data and/or send mail that you could use instead.

**Comment by JonDevOps** [comment]
Awesome thank you! I dont want to change hosts quite yet since we do not actually need the mail php I plan on changing that to a sign up form instead of a mail form. Sign up as in a way to sign into the future user profiles...maybe i should comment out that section until i setup a admin panel and user profiles and change hosts and purchase a ssl...

**Comment by JonDevOps** [comment]
so i think that means we do not need that mail file either then :)

**Comment by waterlgndx** [comment]
Yeah I don't know that you'd be able to create user profiles and such without it being on a separate host or make use of external stuff like Google app engine (probably could use AWS or other similar back end offerings)

**Comment by JonDevOps** [comment]
Hmm i didnt know that, but it sounds right. But before i switch hosts i need to purchase a few things to be secure, such as a proper ssl.

**Comment by JonDevOps** [comment]
I see you are learning android development and gps, thats great because i would love to implement that into a app for users to schedule local meetups...wait let me make a issue for that :D
